### ISSUE TITLE
Current npm build broken

### ISSUE THREAD

**Issue by guyfedwards** [jackellenberger/emojme#25]
`emojme.js` requires many sibling files that are not there in the npm dist, they have been moved to `lib`.

I would have fixed this quickly but couldn't see how you were doing the release and moving stuff into `lib` so couldn't help. If you point me in the right direction I can amend this and submit a PR :ok_hand:

**Comment by jackellenberger** [comment]
That's weird! I have the lib folder included [right here](https://github.com/jackellenberger/emojme/blob/master/package.json#L20) but maybe it doesn't know how to deal with directories recursively?

I've been testing the package with `npm link`, maybe that's not robust enough. There's no magic moving things around, I just `npm login && npm publish` when I've got a change. Let me see if I can sort this out

**Comment by guyfedwards** [comment]
Are the `lib` files copies of the `emojme-...` files of the same name in root?

**Comment by jackellenberger** [comment]
No, so the lib files are supposed to be "project neutral" ways to interface with the slack api (e.g. hitting the `emoji.adminList` endpoint in `emoji-admin-list` and hitting the `emoji.add` endpoint in `emoji-add`) and the `emojme-*` do the actual grunt work of taking user input, requesting input from the slack "lib", and dealing with the output. 

The line has definitely gotten fuzzier and was not helped by my naming scheme.

Anyway, after actually installing the package instead of npm linking i can see the problem, and the fix should be simple. gimme 2 secs.

**Comment by guyfedwards** [comment]
Nice :ok_hand:

**Comment by guyfedwards** [comment]
Works :taco:
