### ISSUE TITLE
found 2 vulnerabilities (1 low, 1 moderate)

### ISSUE THREAD

**Issue by takanakahiko** [jackellenberger/emojme#39]
I get warning `found 2 vulnerabilities (1 low, 1 moderate)` when running `npm i` .

Details :
![image](https://user-images.githubusercontent.com/10114717/50638023-937a6700-0f9f-11e9-84d6-81ace7c5f444.png)

Need to update dependencies.

**Comment by takanakahiko** [comment]
This problem is due to `superagent-throttle`.

https://github.com/leviwheatcroft/superagent-throttle/issues/13

**Comment by jackellenberger** [comment]
Thanks @takanakahiko, it looks like superagent-throttle has been fixed, but not released. I @'d the maintainer and we'll see if they get back to me in a reasonable amount of time. If not, my options are:

1) make the dependency a github one instead of an npm one (easy but also ew)
2) for the repo and make the dependency a github one that i can control / make sure doesn't get turned into malware
3) implement my own throttling idk doesn't seem that bad

For you, for the time being, you can clear up the vulnerability in your own project by editing your package-lock.json to have superagent-throttle require superagent@3.8.3 instead of superagent@1.x.x. Then just delete your node modules and reinstall.

**Comment by jackellenberger** [comment]
Okay! The author just released superagent-throttle@1.0.0 with the fix, and I've committed it to master. Expect emojme@1.5.1 soon.

**Comment by takanakahiko** [comment]
Thanks!

**Comment by jackellenberger** [comment]
Sorry for the delay, [emojme@1.5.1](https://www.npmjs.com/package/emojme/v/1.5.1) is out with superagent-throttle's fix. thanks for your patience!
